apiVersion: kvint/v1
kind: component
namespace: default
id: payment-service
name: Payment Service

owner: group:default/
lifecycle: experimental
type: service

system: ""
domain: ""

tags: []

links: []

contracts:
  - protocol: http
    path: openapi/openapi.yaml

dependsOn: []
